export { DetailPage } from './detailpage'
export { Speakers } from './Speakers'
export { NotFound } from './NotFound'
export { Headphones } from './Headphones'
export { Earphones } from './Earphones'
export { Home } from './home'
export { Checkout } from './checkout'
